apiVersion: v1
kind: Service
metadata:
  name: sample-html-app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001  # You can choose a port in the range 30000-32767
  selector:
    app: sample-html-app